-- ============================================================================
-- Inventario de Almacén Regional — esquema de Supabase
-- Ejecuta este script completo en Supabase → SQL Editor → New query → Run
-- ============================================================================

-- Tabla principal de inventario (todo lo que está actualmente en el almacén)
create table if not exists public.inventario (
  id          text primary key,
  material    text not null,
  fecha       date,
  proyecto    text,
  pae         text,
  v1          text,
  v2          text,
  v3          text,
  cond        text default 'N/A',
  cant        text default '1',
  rack        text default 'N/A',
  created_at  timestamptz not null default now()
);

-- Historial de salidas (se agrega una fila cada vez que un ítem sale del almacén)
create table if not exists public.salidas (
  id          bigint generated by default as identity primary key,
  item_id     text not null,
  material    text,
  motivo      text,
  nota        text,
  fecha       date not null default current_date,
  created_at  timestamptz not null default now()
);

-- Row Level Security: solo usuarios autenticados (los del equipo, creados en
-- Authentication → Users) pueden leer y escribir. No hay acceso público.
alter table public.inventario enable row level security;
alter table public.salidas enable row level security;

drop policy if exists "authenticated_full_access" on public.inventario;
create policy "authenticated_full_access" on public.inventario
  for all
  to authenticated
  using (true)
  with check (true);

drop policy if exists "authenticated_full_access" on public.salidas;
create policy "authenticated_full_access" on public.salidas
  for all
  to authenticated
  using (true)
  with check (true);

-- Índices útiles para los filtros de la pestaña "Buscar"
create index if not exists inventario_material_idx on public.inventario (material);
create index if not exists inventario_cond_idx on public.inventario (cond);
create index if not exists inventario_rack_idx on public.inventario (rack);

-- ----------------------------------------------------------------------------
-- Datos de ejemplo (opcional). Comenta o borra este bloque si no los quieres.
-- ----------------------------------------------------------------------------
insert into public.inventario (id, material, fecha, proyecto, pae, v1, v2, v3, cond, cant, rack) values
  ('60443','TANQUE','2024-08-05','NIS P13C SOR FWD ORVR','ANDERSON CARVALHO','FUEL GAUGE CHARACTERISTICS','','','POR DISPONERSE','1','7'),
  ('61913','TANQUE','2025-08-13','POLARIS ENCORE','JOSE CAVALCANTE','DROP IMPACT','SOAKING','','POR DISPONERSE','1','7'),
  ('51513','FIXTURE BUCK','2026-01-26','CHR DD/DP','','','','','N/A','1','N/A')
on conflict (id) do nothing;
